version: "3.8"

services:
  federation:
    image: "neurobagel/federation_api:latest"
    ports:
      - "8000:8000"
    volumes:
      - "./local_nb_nodes.json:/usr/src/local_nb_nodes.json:ro"
    environment:
      NB_API_PORT: 8000
  
  query:
    image: "neurobagel/query_tool:v0.1.0"
    ports:
      - "3000:5173"
    environment:
      NB_API_QUERY_URL: "http://localhost:8000/"

  api1:
    image: "neurobagel/api:latest"
    ports:
      - "8001:8000"
    environment:
      NB_GRAPH_USERNAME: dev_user
      NB_GRAPH_PASSWORD: dev_password
      NB_GRAPH_ADDRESS: graph
      NB_GRAPH_PORT: 7200
      NB_GRAPH_DB: repositories/db1
      NB_RETURN_AGG: false
      NB_API_PORT: 8000
      NB_API_ALLOWED_ORIGINS: "*"

  api2:
    image: "neurobagel/api:latest"
    ports:
      - "8002:8000"
    environment:
      NB_GRAPH_USERNAME: dev_user
      NB_GRAPH_PASSWORD: dev_password
      NB_GRAPH_ADDRESS: graph
      NB_GRAPH_PORT: 7200
      NB_GRAPH_DB: repositories/db2
      NB_RETURN_AGG: false
      NB_API_PORT: 8000
      NB_API_ALLOWED_ORIGINS: "*"

  graph:
    image: "ontotext/graphdb:10.3.1"
    ports:
      - "7200:7200"
    volumes:
      - "./graphdb_entrypoint.sh:/opt/graphdb_entrypoint.sh"
      - "./data-config_template.ttl:/opt/data-config_template.ttl"
      - "./:/data/"
    entrypoint: ["/opt/graphdb_entrypoint.sh"]